import type { Metadata } from 'next'
import '../../style.css'
import { SiteHeader } from '@/src/components/SiteHeader'
import { OrderDock } from '@/src/components/OrderDock'
import { SettingsSync } from '@/src/components/client/SettingsSync'
import { getLatestIssue, getSettings } from '@/src/lib/store'
export const metadata:Metadata={title:{default:'SHATI — Uniforms are for school',template:'%s — SHATI'},description:'Independent menswear from Nairobi. Shop the rail, watch SHATI, and represent your county.',metadataBase:new URL(process.env.NEXT_PUBLIC_SERVER_URL||'http://localhost:3000')}
export const dynamic='force-dynamic'
export default async function SiteLayout({children}:{children:React.ReactNode}){const [settings,issue]=await Promise.all([getSettings(),getLatestIssue()]);const phone=settings.shopPhone||'+254 729 286626';const greeting=settings.whatsappGreeting||'Hi SHATI, I have a question.';const number=issue?.number||'00';return <html lang="en"><head><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/><link href="https://fonts.googleapis.com/css2?family=Anton&family=Archivo:wght@400;500;600;700&family=Instrument+Serif:ital@1&family=Newsreader:ital,opsz,wght@1,6..72,400;1,6..72,500&display=swap" rel="stylesheet"/></head><body><SettingsSync phone={phone} greeting={greeting}/><SiteHeader phone={phone} greeting={greeting} issueNumber={number} ticker={settings.tickerText||'NAIROBI CBD · DELIVERY TO ALL 47 COUNTIES'}/><main id="main">{children}</main><footer className="footer"><div className="footer-top"><img src="/assets/shati-wordmark-night.svg" alt="SHATI"/><span>{settings.storeAddress||'Nairobi, Kenya'}<br/>{settings.openingHours||'Independent menswear, made to be worn.'}</span><div><a href="/shop">Shop</a><a href="/watch">Watch</a><a href="/league">League</a><a href={`https://wa.me/${phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">WhatsApp ↗</a></div></div><div className="footer-bottom"><span>© SHATI {new Date().getFullYear()}</span><span>NAIROBI · EVERYWHERE</span><a href="#top">BACK TO TOP ↑</a></div></footer><OrderDock/></body></html>}
