'use client'
import { useState } from 'react'
import Link from 'next/link'
import { VideoPlayer } from './VideoPlayer'
import { formatKES } from '@/src/lib/format'

const tabs=['Counties','Managers','This month']
const countiesFallback=['Mombasa','Kwale','Kilifi','Tana River','Lamu','Taita-Taveta','Garissa','Wajir','Mandera','Marsabit','Isiolo','Meru','Tharaka-Nithi','Embu','Kitui','Machakos','Makueni','Nyandarua','Nyeri','Kirinyaga','Murang’a','Kiambu','Turkana','West Pokot','Samburu','Trans Nzoia','Uasin Gishu','Elgeyo-Marakwet','Nandi','Baringo','Laikipia','Nakuru','Narok','Kajiado','Kericho','Bomet','Kakamega','Vihiga','Bungoma','Busia','Siaya','Kisumu','Homa Bay','Migori','Kisii','Nyamira','Nairobi']

export function LeagueClient({counties,snapshot,products=[],episode,memberPricePercent}:{counties:{id:string,name:string}[];snapshot:any;products?:any[];episode?:any;memberPricePercent?:number}){
  const [tab,setTab]=useState('Counties')
  const [status,setStatus]=useState('')
  const records=tab==='Counties'?snapshot?.countyTable:tab==='Managers'?snapshot?.managerTable:snapshot?.monthTable
  const rows=Array.isArray(records)?records:[]
  async function join(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();setStatus('Checking your FPL team…')
    const form=new FormData(e.currentTarget)
    try{
      const response=await fetch('/api/league/join',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fplTeamId:form.get('fplTeamId'),county:form.get('county'),whatsapp:form.get('whatsapp'),weeklyTableOptIn:form.get('weeklyTableOptIn')==='on',uniformOptIn:form.get('uniformOptIn')==='on'})})
      const data=await response.json();if(!response.ok)throw new Error(data.error||'We could not complete your entry.')
      window.location.assign(data.whatsappUrl)
    }catch(error){setStatus(error instanceof Error?error.message:'Please try again.')}
  }
  return <>
    <div className="league-intro"><div><p className="hero-copy">Fantasy Premier League, played together. Pick your county, bring your team, and follow the table every gameweek.</p><div className="rules"><h2>Free to play. No prizes.</h2><p>Joining is free and never requires a purchase. Every member gets the same member price. League position carries no reward. We play for county pride.</p></div></div>
      <form className="join-card" onSubmit={join}><span className="eyebrow">Season {process.env.NEXT_PUBLIC_FPL_SEASON||'2026/27'}</span><h2>Join the league.</h2><p className="fine" style={{marginBottom:14}}>No account. No purchase needed.</p><div className="form-grid"><div className="field"><label htmlFor="fplid">FPL team ID</label><input id="fplid" name="fplTeamId" inputMode="numeric" pattern="[0-9]+" required/></div><div className="field"><label htmlFor="league-county">County</label><select id="league-county" name="county" required>{(counties.length?counties:countiesFallback.map(name=>({id:'',name}))).map(c=><option value={c.name} key={c.name}>{c.name}</option>)}</select></div><div className="field wide"><label htmlFor="league-phone">WhatsApp number</label><input id="league-phone" name="whatsapp" type="tel" placeholder="07XX XXX XXX" required pattern="(?:\+?254|0)[17][0-9]{8}"/></div><label className="wide fine check-label"><input type="checkbox" name="weeklyTableOptIn"/> Send me the weekly table on WhatsApp</label><label className="wide fine check-label"><input type="checkbox" name="uniformOptIn"/> I understand and opt in to the Uniform forfeit</label></div><button className="button">Join the league <span>↗</span></button><p className="fine" role="status" aria-live="polite">{status}</p></form>
    </div>
    <section className="section"><div className="section-head"><div><span className="eyebrow">{snapshot?`GW ${snapshot.gameweek} · Updated ${new Date(snapshot.updatedAt).toLocaleString('en-KE')}`:'County table'}</span><h2>The table.</h2></div><p>County scores average the five highest ranked managers in each squad. Fair play across every county.</p></div><div className="league-tabs" role="tablist">{tabs.map(name=><button role="tab" aria-selected={tab===name} aria-pressed={tab===name} key={name} onClick={()=>setTab(name)}>{name}</button>)}</div>
      {rows.length?<div style={{overflow:'auto'}}><table className="table"><thead><tr><th>#</th><th></th><th>{tab==='Managers'?'Manager':'County'}</th><th>{tab==='This month'?'Month':'GW'}</th><th>{tab==='This month'?'Season':'Tot'}</th></tr></thead><tbody>{rows.slice(0,30).map((row:any,index:number)=><tr key={row.id||row.countyId||row.name||index}><td>{row.rank||index+1}</td><td aria-label={`Movement ${row.movement||'unchanged'}`}>{row.movement==='up'?'▲':row.movement==='down'?'▼':'—'}</td><td><strong>{row.name}</strong><br/><span className="fine">{row.subline||row.county||''}</span>{row.needsSquad&&row.recruitMessage&&<a className="fine recruit-link" href={`https://wa.me/?text=${encodeURIComponent(row.recruitMessage)}`} target="_blank" rel="noreferrer">Invite a manager ↗</a>}</td><td>{row.gameweekPoints??'—'}</td><td>{row.totalPoints??'—'}</td></tr>)}</tbody></table></div>:<p>The next county table will appear after the first gameweek updates.</p>}
      <p className="fine" style={{marginTop:14}}>County squads contain five managers. Counties with fewer than five members are shown as needing a squad.</p>
    </section>
    <section className="section"><div className="section-head"><div><span className="eyebrow">The rules</span><h2>How we play.</h2></div></div><div className="rules"><h2>Squad of five.</h2><p>At each gameweek deadline, each county’s five highest ranked SHATI managers form its squad. The county’s gameweek score is their average. The season table adds each gameweek score.</p></div><p>Joining is free. A purchase is never required. League position does not earn a reward. All members receive the same member price.</p></section>
    {episode&&<section className="section"><div className="section-head"><div><span className="eyebrow">This week on The Gameweek</span><h2>Watch the table.</h2></div></div><div className="watch-feature"><VideoPlayer youtubeId={episode.youtubeId} title={episode.title}/><div><span className="eyebrow">{episode.show?.name}</span><h2 className="page-title" style={{fontSize:38}}>{episode.title}</h2><p>County football, gameweek points, and the latest from the league.</p></div></div></section>}
    <section className="section"><div className="section-head"><div><span className="eyebrow">The same for every league member</span><h2>Member price.</h2></div><p>{memberPricePercent?`${memberPricePercent}% off selected SHATI pieces for every member.`:'Member pricing details will be added by SHATI. Every member receives the same price.'}</p></div><div className="products">{products.map((product:any)=><Link href={`/shop/${product.slug}`} className="product-card" key={product.id}><div className="product-art">{product.gallery?.[0]?.url&&<img src={product.gallery[0].url} alt={product.gallery[0].alt||product.name} style={{width:'100%',height:'100%',objectFit:'cover',position:'absolute',inset:0}}/>}</div><span className="product-meta">{product.category}</span><span className="product-name">{product.name}</span><span>{formatKES(product.price)}</span><span className="fine">Same member price for all members</span></Link>)}</div>{!products.length&&<p>Member price pieces will appear here as the rail is updated.</p>}</section>
  </>
}
